# Generated by Django 3.0.2 on 2020-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('web_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
